export const languageOptions = [
    {label: 'English', value:'/auto/en'},
    {label: 'हिन्दी', value:'/auto/hi'},
    {label: 'বাংলা', value:'/auto/bn'},
    {label: 'తెలుగు', value:'/auto/te'},
    {label: 'मराठी', value:'/auto/mr'},
    {label: 'தமிழ்', value:'/auto/ta'},
    {label: 'ગુજરાતી', value:'/auto/gu'},
    {label: 'ಕನ್ನಡ', value:'/auto/kn'},
    {label: 'മലയാളം', value:'/auto/ml'},
    {label: 'ਪੰਜਾਬੀ', value:'/auto/pa'},
    {label: 'اردو', value:'/auto/ur'},
    {label: 'ଓଡ଼ିଆ', value:'/auto/or'},
    {label: 'Asụsụ Igbo', value:'/auto/ig'},
    {label: 'Yorùbá', value:'/auto/yo'},
    {label: 'አማርኛ', value:'/auto/am'},
    {label: 'नेपाली', value:'/auto/ne'},
    {label: '日本語', value:'/auto/ja'},
    {label: '中文', value:'/auto/zh'},
    {label: '한국어', value:'/auto/ko'},
    {label: 'Soomaali', value:'/auto/so'},
    {label: 'Kiswahili', value:'/auto/sw'},
    {label: 'Kinyarwanda', value:'/auto/rw'},
    {label: 'ChiShona', value:'/auto/sn'},
    {label: 'isiZulu', value:'/auto/zu'},
    {label: 'isiXhosa', value:'/auto/xh'},
    {label: 'SiSwati', value:'/auto/ss'},
    {label: 'Sesotho', value:'/auto/st'},
    {label: 'Setswana', value:'/auto/tn'},
    {label: 'Afrikaans', value:'/auto/af'},
    {label: `Русский`, value:'/auto/ru'},
    {label: 'Polski', value:'/auto/pl'} 
];